hyperparameters:
  learning_rate: 1e-6
accelerator: "cpu"
max_epochs: 1
max_steps: -1
num_workers: 20
batch_size: 16
input:
  suffix: "silver"
  train: "train"
  test: "test"
  valid: "valid"
tracking_uri: "databricks"
experiment_name: "/Shared/dbx/insuranceqa"
